### PR TITLE
Sets encoding to UTF-8 to resolve #13

### LINKED ISSUE #13: Databases require character set utf8
https://www.cloudera.com/documentation/enterprise/latest/topics/install_cm_mariadb.html#install_cm_mariadb_newdbs

### PR DESCRIPTION
**Pull request by rafaelarana**
Sets encoding to UTF-8 during database creation

### CODE REVIEW

**Review by jnowakowski — CHANGES_REQUESTED** [review]
Not a right file committed to solve encoding. Possible mistake.

**Comment by lhoss** [comment]
this PR can be closed
the right PR (by the title) is https://github.com/cloudera/cloudera-playbook/pull/17

**Comment by roczei** [comment]
Hi @rafaelarana and @jnowakowski,

You need to first sign and return an ICLA and CCLA before we can accept and redistribute your contribution. Once these are submitted you are free to start contributing to cloudera-playbook. Submit these to CLA@cloudera.com

Here you can find the pdf files:

https://github.com/cloudera/cloudera-playbook/tree/master/icla

Please update this issue (14) if you receive the confirmation from our CLA team.

Thank you!

**Comment by roczei** [comment]
I am closing this pull request because the right PR is #17

**Pull request closed without merging**
