### PR TITLE
Corrected mariadb pid file location

### PR DESCRIPTION
**Pull request by Jimvin**
On CentOS 7 mariadb creates the pid file in /var/run/mariadb, not /var/run/mysql. Installation using the playbooked worked, but mariadb would not start following reboot of the DB server.

### CODE REVIEW

**Comment by dbeech** [comment]
I think mariadb should put the file where we tell it to, but we're setting the `pid-file` option in `my.cnf` incorrectly. We're putting it in a `[mysqld_safe]` block rather than further up in the main `[mysql]` block.

**Comment by dbeech** [comment]
Ok, ignore that last comment. It doesn't fix it and I understand why now. 
It makes me wonder why we bother to set `mysql_pid_dir` and `mysql_pid_file` in the template at all? Surely leaving it to the defaults would be ok and then it will work on all platforms?

**Comment by Jimvin** [comment]
Agreed, removing it from the configuration would seem to be the best option.

**Comment by dbeech** [comment]
Closing as fixed by @rafaelarana's PR #12.

**Pull request closed without merging**
