### PR TITLE
zookeeper template is missing the kerberos security configurations

### PR DESCRIPTION
**Pull request by anis016**
Zookeeper Kerberos security configuration is missing.

### CODE REVIEW

**Comment by dbeech** [comment]
Thanks @anis016! Not sure how we missed this one. Will test and merge asap.

**Comment by dbeech** [comment]
@anis016 - before we can merge your patch there is (unfortunately) some legal paperwork we need to get out of the way. Please could you check the instructions [here](https://github.com/cloudera/cloudera-playbook#how-do-i-contribute-code) and let me know if you have any issues?

**Comment by anis016** [comment]
@dbeech - I already sent the paper to CLA@cloudera.com on 20th September

**Comment by dbeech** [comment]
Excellent, thanks!

**Pull request merged**
